version: '3.8'

services:
  config-change-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: config-change-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - config-change-logs:/app/logs

volumes:
  config-change-logs: